// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frlmzgopqqxjaapfixsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZybG16Z29wcXF4amFhcGZpeHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzczNDgsImV4cCI6MjA3MDc1MzM0OH0.IZGOEwlGSc65atbvdE_kRAITcfUDCd9iPWN3PtLFhbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});